In [2]:
import cv2
import numpy as np

# Load/Read image

In [3]:
# Load an image using 'imread' specifying the path tonimage
img = cv2.imread(r"C:\Users\subha\Downloads\Modi.jpg",1)

###  Let's take a closer look at how images are stored

In [4]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


##  Shape gives the dimensions of the image array

In [5]:
img.shape

# The 3D dimensions are 1358 pixel in height * 1500 0ixels wide
# 3 means that there are 3 components (RGB) that make up this image

(1358, 1500, 3)

## Display the image

In [6]:
# TO display our image variable ,we have 'imshow'
# The first parameter will be title show on image window
# the second parameter is the image variable
cv2.imshow('PM',img)

# Waitkey allows us to input information when a image is open
# By leaving it blanck it just waits for anykey to be pressed before continiuing
# By placing number (except ,0 ), we can specify a delay for
# How long you keep the window open(time is in milisecond here)
cv2.waitKey(2000)

# This closes all open window
# Failure to place this will cause your program to hang
cv2.destroyAllWindows()

In [7]:
img = cv2.imread(r"C:\Users\subha\Downloads\Modi.jpg")
cv2.imshow('PM',img)
cv2.waitKey()
cv2.destroyAllWindows()

##  Resize image

In [8]:
img = cv2.imread(r"C:\Users\subha\Downloads\Modi.jpg")

resized_image = cv2.resize(img,(500,500))

gray = cv2.cvtColor(resized_image, cv2.COLOR_BGR2GRAY)

cv2.imshow('Modi Image',gray)

cv2.waitKey()
cv2.destroyAllWindows()

In [9]:
img.shape[0]*0.5

679.0

In [10]:
img.shape[1]*0.5

750.0

## 

##  Face detection using HAAR Cascade classifier

In [11]:
# we print opencv's Cascade classifier function to where our classifier (xml file format) is stored
face_classifier = cv2.CascadeClassifier(r"C:\Users\subha\Downloads\haarcascade_frontalface_default.xml")

# load our image then convert it to grayscale
image = cv2.imread(r"C:\Users\subha\Downloads\Modi.jpg")
image = cv2.resize(img,(500,500))
gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

# Tuning cascade classifiers - detectmultiscale (input image,**scale factor**,**Min Neighbors**))
faces = face_classifier.detectMultiScale(gray,1.05,5)

# scale factor - specifies how much we reduce the image size each time we scale
# E.g. in face detection we tipycally use 1.3 .this means we reduce the image by 30% each time its shape
# smaller values, like 1.05 will take longer to compute, but will increase the rate  of detection

## Min Neighbors**
# Specifies the number of neighbors each potential window should have in order to consider it a positive detection
# Typically set between 3-6.
# It act sensitively setting ,low values will sometimes detect multiples faces over a single face.
# High values will ensure less false positive ,but you may miss some faces.

In [12]:
print(faces)

[[205  79 217 217]]


In [13]:
face_classifier = cv2.CascadeClassifier(r"C:\Users\subha\Downloads\haarcascade_frontalface_default.xml")

# load our image then convert it to grayscale
image = cv2.imread(r"C:\Users\subha\Downloads\Modi.jpg")
image = cv2.resize(img,(500,500))
gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)


faces = face_classifier.detectMultiScale(gray,1.05,5)


# when no face detected , face_classifier returns and empty tuple
if faces is():
    print("No face found")
    
# we iterate through our faces array and draw a rectangle
# over each face in faces
for (x,y,w,h) in faces:
    cv2.rectangle(image,(x,y),(x+w,y+h),(255,0,100),1)
# in this line (255,0,100) meand that as color BGR respectively

cv2.imshow('Face Detection',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

<>:13: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:13: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\subha\AppData\Local\Temp\ipykernel_9960\1921228271.py:13: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is():


#  Face & eye detection using HAAR CAscade Classifier in image

In [14]:
face_classifier = cv2.CascadeClassifier(r"C:\Users\subha\Downloads\haarcascade_frontalface_default.xml")
eye_classifier = cv2.CascadeClassifier(r"C:\Users\subha\Downloads\haarcascade_eye.xml")

img = cv2.imread(r"C:\Users\subha\Downloads\Modi.jpg")
resized_image = cv2.resize(img,(500,500))
gray = cv2.cvtColor(resized_image,cv2.COLOR_BGR2GRAY)

faces = face_classifier.detectMultiScale(gray,1.3,5)

# when no faces detected ,face_classifier returns and empty tuple
if faces is ():
    print("No Face Found")
    
for (x,y,w,h) in faces:
    cv2.rectangle(resized_image,(x,y),(x+w,y+h),(255,0,0),2)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = resized_image[y:y+h, x:x+w]
    eyes = eye_classifier.detectMultiScale(roi_gray)
    for(ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
cv2.imshow('img',resized_image)
cv2.waitKey(0)

cv2.destroyAllWindows()

<>:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\subha\AppData\Local\Temp\ipykernel_9960\2304791087.py:11: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


##  Capture a video

In [15]:
# Doing some face Recognition with the webcam
import cv2
video = cv2.VideoCapture(0)  # 0---> webcam

while True:
    check, frame = video.read()
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow('video',gray)
    if cv2.waitKey(1) == ord('q'):
        break
# to get a color video no need to define gray ,and  ('video',gray) use frame inplace of gray       
video.release()
cv2.destroyAllWindows()

##  FAce Eye Detection using HAAR Cascade Classifier with video

In [16]:
# Defining a function that will do the detection
face_cascade = cv2.CascadeClassifier(r"C:\Users\subha\Downloads\haarcascade_frontalface_default.xml")
eye_cascade = cv2.CascadeClassifier(r"C:\Users\subha\Downloads\haarcascade_eye.xml")

def detect(gray,frame):
    faces = face_cascade.detectMultiScale(gray,1.3,5)
    
    for (x,y,w,h) in faces:
        cv2.rectangle(resized_image,(x,y),(x+w,y+h),(255,0,0),2)
        roi_gray = gray[y:y+h, x:x+w]
        roi_color = resized_image[y:y+h, x:x+w]
        eyes = eye_classifier.detectMultiScale(roi_gray)
        for(ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
    return frame

# Doing some face recognization with the webcam
video = cv2.VideoCapture(0)  # 0---> webcam

while True:
    check, frame = video.read()
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    canvas = detect(gray,frame)
    cv2.imshow('video',gray)
    if cv2.waitKey(1) == ord('q'):
        break
# to get a color video no need to define gray ,and  ('video',gray) use frame inplace of gray       
video.release()
cv2.destroyAllWindows()

    
    

##  Pedistrian Detection

In [18]:
import cv2

# create our body classifier
body_classifier = cv2.CascadeClassifier(r'C:\Users\subha\Downloads\haarcascade_fullbody.xml')

# Intimate video capture from video file
cap = cv2.VideoCapture(r'C:\Users\subha\Downloads\walking.avi')

# loop once video is successfully loaded
while cap.isOpened():
    # read first frame
    check, frame=cap.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    # pass frame to our body classifier
    bodies = body_classifier.detectMultiScale(gray,1.2,3)
    
    # Extract bunding boxes for any bodies identified
    for (x,y,w,h) in bodies:
        cv2.rectangle(frame,(x,y),(x+w, y+h),(0,255,255),2 )
        cv2.imshow('Pedestrians',frame)
        

    if cv2.waitKey(1)==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

In [20]:
import time

# create our body classifier
car_classifier = cv2.CascadeClassifier(r'C:\Users\subha\Downloads\haarcascade_car.xml')

# Intimate video capture from video file
cap = cv2.VideoCapture(r'C:\Users\subha\Downloads\cars.avi')

# loop once video is successfully loaded
while cap.isOpened():
    time.sleep(.05)
    
    # read first frame
    check, frame=cap.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    # pass frame to our body classifier
    cars = car_classifier.detectMultiScale(gray,1.2,3)
    
    # Extract bunding boxes for any bodies identified
    for (x,y,w,h) in cars:
        cv2.rectangle(frame,(x,y),(x+w, y+h),(0,255,255),2 )
        cv2.imshow('Cars',frame)
        

    if cv2.waitKey(1)==ord('e'):
        break
        
cap.release()
cv2.destroyAllWindows()
